// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ass
NumericMatrix ass(int n);
RcppExport SEXP hw6_ass(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(ass(n));
    return __result;
END_RCPP
}
// mode
int mode(IntegerVector x);
RcppExport SEXP hw6_mode(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    __result = Rcpp::wrap(mode(x));
    return __result;
END_RCPP
}
// qgramdist
double qgramdist(IntegerVector x, IntegerVector y, int q);
RcppExport SEXP hw6_qgramdist(SEXP xSEXP, SEXP ySEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    __result = Rcpp::wrap(qgramdist(x, y, q));
    return __result;
END_RCPP
}
